client_config_backend: settings
client_config:
  client_id: "1078095588487-n8vlfco0lgvif8qdbmmuel4s3q8j13vm.apps.googleusercontent.com"
  client_secret: "UBCrjYl0x2N55anDVYemdsRk"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install